### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'remove_callback'

### ISSUE THREAD

**Issue by Zach-Richardson** [joshjohnston/Teaching#1]
I get the following error when running in Jupyter notebook using Anaconda3

`
Traceback (most recent call last):
  File "/home/zach/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/home/zach/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1478, in _stop
    self.event_source.remove_callback(self._loop_delay)
AttributeError: 'NoneType' object has no attribute 'remove_callback'
`

**Comment by Zach-Richardson** [comment]
Found a couple SO threads that may be helpful. Seems to be related to reference to FuncAnimation. 

https://stackoverflow.com/questions/42964565/matplotlib-animation-attributeerror-nonetype-object-has-no-attribute-new-t

https://stackoverflow.com/questions/42815385/python-error-using-animation-funcanimation/42834862#42834862
